import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e8e3",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f1f1ec",
        "on-primary-container": "#70a380",
        "on-primary-fixed": "#00210f",
        "surface-bright": "#fafaf4",
        outline: "#717971",
        "primary-container": "#01381e",
        "surface-tint": "#38684a",
        "surface-dim": "#dadad5",
        "on-surface": "#1a1c19",
        "on-primary-fixed-variant": "#1f5033",
        "error-container": "#ffdad6",
        primary: "#00200f",
        "primary-fixed": "#baefc8",
        error: "#ba1a1a",
        "outline-variant": "#c0c9c0",
        "on-primary": "#ffffff",
        background: "#fafaf4",
        "on-tertiary-fixed-variant": "#454744",
        "secondary-fixed-dim": "#c6ca9b",
        surface: "#fafaf4",
        "surface-variant": "#e3e3de",
        "on-surface-variant": "#414942",
        "secondary-fixed": "#e2e6b5",
        "inverse-surface": "#2f312e",
        "inverse-primary": "#9ed3ad",
        secondary: "#5d613a",
        "surface-container-lowest": "#ffffff",
        tertiary: "#191c19",
        "on-secondary-fixed": "#1a1d01",
        "surface-container": "#eeeee9",
        "on-background": "#1a1c19",
        "surface-container-low": "#f4f4ee",
        "surface-container-highest": "#e3e3de",
        "on-tertiary-container": "#979994",
        "on-secondary-container": "#61663e",
        "primary-fixed-dim": "#9ed3ad",
        "tertiary-container": "#2e312e",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#1a1c19",
        "on-secondary-fixed-variant": "#454925",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-container": "#dfe3b2",
        "tertiary-fixed": "#e2e3de",
        "tertiary-fixed-dim": "#c6c7c2",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "40px",
        "stack-lg": "32px",
        gutter: "24px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "section-gap": "80px",
        "container-max": "1200px",
        base: "8px",
        "stack-md": "16px",
      },
      fontFamily: {
        "headline-md": ["var(--font-hanken-grotesk)"],
        "label-sm": ["var(--font-hanken-grotesk)"],
        "body-lg": ["var(--font-work-sans)"],
        "label-md": ["var(--font-hanken-grotesk)"],
        "headline-lg-mobile": ["var(--font-hanken-grotesk)"],
        "body-sm": ["var(--font-work-sans)"],
        "body-md": ["var(--font-work-sans)"],
        "headline-xl": ["var(--font-hanken-grotesk)"],
        "headline-lg": ["var(--font-hanken-grotesk)"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
